dist: trusty
language: cpp

os:
  - linux

compiler:
  - gcc
  #- clang

env:
  - BUILD_CONFIGURATION=Debug
  - BUILD_CONFIGURATION=Release

script:
  - mkdir build
  - cd build
  - cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=$BUILD_CONFIGURATION -DCMAKE_INSTALL_PREFIX=deploy ..
  - cmake --build . --config $BUILD_CONFIGURATION
  - ctest -C $BUILD_CONFIGURATION --verbose
