dist: trusty
language: cpp
sudo: required

os:
  - linux

compiler:
  - gcc
  #- clang

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install: 
  - sudo apt-get install -qq g++-6
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 90

env:
  - BUILD_CONFIGURATION=Debug
  - BUILD_CONFIGURATION=Release

script:
  - mkdir build
  - cd build
  - cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=$BUILD_CONFIGURATION -DCMAKE_INSTALL_PREFIX=deploy ..
  - cmake --build . --config $BUILD_CONFIGURATION
  - ctest -C $BUILD_CONFIGURATION --verbose
