dist: bionic
language: cpp

notifications:
  email: false

os:
  - linux

compiler:
  - g++
  #- clang

before_install:
  - g++ --version
  - cmake --version

env:
  - config=Debug
  - config=Release

script:
  - mkdir build
  - cd build
  - cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=$config -DCMAKE_INSTALL_PREFIX=deploy ..
  - cmake --build . --config $config
  - cmake --build . --config $config --target install
  - ctest -C $config --verbose

