dist: trusty
language: cpp
sudo: required

os:
  - linux

compiler:
  - gcc
  #- clang

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-5
    - g++-5

env:
  - BUILD_CONFIGURATION=Debug
  - BUILD_CONFIGURATION=Release

script:
  - sudo unlink /usr/bin/gcc && sudo ln -s /usr/bin/gcc-5 /usr/bin/gcc
  - gcc --version

  - mkdir build
  - cd build
  - cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=$BUILD_CONFIGURATION -DCMAKE_INSTALL_PREFIX=deploy ..
  - cmake --build . --config $BUILD_CONFIGURATION
  - ctest -C $BUILD_CONFIGURATION --verbose
