version: 1.0.{build}

environment:
  matrix:
    - msvc_ver: Visual Studio 15 2017

configuration:
  - Debug
  - Release

platform:
  - x86
  - x64

clone_folder: c:\projects\mix

build_script:
  - set build_folder=build_msvc_%platform%
  - mkdir %build_folder%
  - cd %build_folder%
  - if "%platform%"=="x86" (set generator="%msvc_ver%")
  - if "%platform%"=="x64" (set generator="%msvc_ver% Win64")
  - cmake -G %generator% ..
  - cmake --build . --config %configuration%

test_script:
  - ctest -C %configuration% --verbose
