version: 1.0.{build}
image:
  - Visual Studio 2019

matrix:
  fast_finish: true

environment:
  matrix:
    - compiler: msvc-19
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      generator: "Visual Studio 16 2019"
      cmake_args: ""
    - compiler: clang-msvc-19
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      generator: "Visual Studio 16 2019"
      cmake_args: "-T LLVM"

configuration:
  - Debug
  - Release

platform:
  - x86
  - x64

cache: c:\tools\vcpkg\installed\

install:
  - cd /d c:\tools\vcpkg
  - vcpkg install gl3w:x64-windows
  - vcpkg install gl3w:x86-windows
  - vcpkg install sdl2:x64-windows
  - vcpkg install sdl2:x86-windows
  - vcpkg install gtest:x64-windows
  - vcpkg install gtest:x86-windows

clone_folder: c:\projects\mix

build_script:
  - cd /d %APPVEYOR_BUILD_FOLDER%
  - set build_folder=build_msvc_%platform%
  - mkdir %build_folder%
  - cd %build_folder%
  - set vcpkg=c:/tools/vcpkg/scripts/buildsystems/vcpkg.cmake
  - cmake -G "%CMake_Generator%" -A %platform% -DCMAKE_TOOLCHAIN_FILE=%vcpkg% -DCMAKE_INSTALL_PREFIX=deploy ..
  - cmake --build . --config %configuration%
  - cmake --build . --config %configuration% --target install

test_script:
  - ctest -C %configuration% --verbose
